### ISSUE TITLE
Implement server side rendering

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [Elite-Kode/elitebgs#120]
Server side rendering with Angular Universal needs to be implemented to improve SEO

**Comment by SayakMukhopadhyay** [comment]
Server side rendering with Angular Universal needs to be implemented to improve SEO

**Comment by vanderaj** [comment]
I think this issue should be closed as you've moved to Vue. I will let you do it, but I think server side rendering is a mistake and will likely lead to cross-site scripting

**Comment by SayakMukhopadhyay** [comment]
Yeah, we can close this. But I am curious as to how SSR can lead to XSS. Shall we talk on Discord about this?
