### ISSUE TITLE
Swagger spec v5 issues

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [Elite-Kode/elitebgs#194]
1. Swagger v5 spec still referencing v4 APIs
2. Uses `integer` for coordinates which is wrong. Should be `number` with `format` as `double`. See https://swagger.io/docs/specification/data-models/data-types/
3. Uses `integer` for population which seems to default to 32bit ints which is too less for billion+ pops,

**Comment by fthevenet** [comment]
1. `influence` should be `number` with format as `double` in:
   * `EBGSFactionPresenceV5`
   * `EBGSFactionHistorySystemV5`
   * `EBGSFactionHistoryV5`
2. `population`should be mapped to a 64 bits integer in:
   * `EBGSSystemHistoryV5`
   * `EBGSSystemsV5`

**Comment by vanderaj** [comment]
@SayakMukhopadhyay I'll take this on.

**Comment by vanderaj** [comment]
I'll also clean up the V1 ... V4 stuff that we can retrieve if necessarily from Git history, rather than leave it hanging around the code. This will make it more maintainable as we move forward into Odyssey, which I am assuming will result in a V6 API.

**Comment by SayakMukhopadhyay** [comment]
From the docs I have seen, it doesn't seem like we will need a new API version after Odyssey is launched as I can probably keep the db structure the same. We should get a doc closer to the actual launch and then I would be able to confirm if there are any changes required.
