### ISSUE TITLE
The "State" column in monitored factions is nearly always wrong

### ISSUE THREAD

**Issue by vanderaj** [Elite-Kode/elitebgs#205]
The Active States column is accurate, but it's almost a triumph of RNG if the "State" column is correct. 

For example, today in c1-13:

![image](https://user-images.githubusercontent.com/5029993/109422554-4769b800-7999-11eb-9b12-be74725679e8.png)

I don't think the front end is broken, because:

![image](https://user-images.githubusercontent.com/5029993/109422849-73d20400-799a-11eb-957a-cf0188f0ad4e.png)

However, in galmap:

![image](https://user-images.githubusercontent.com/5029993/109422589-6d8f5800-7999-11eb-8378-20f0ac3d3e44.png)

The state of Ida in c1-13 should be None, which is the case in eddb.io. I did the scan of this system yesterday and so it should be the same data in eddb.io and EliteBGS.

![image](https://user-images.githubusercontent.com/5029993/109422654-b515e400-7999-11eb-831a-99ddc801514c.png)

This makes the "State" column completely unreliable to base decisions around. Two potential resolutions:

1. Fix the logic that has the incorrect State, or remove the column as Active States generally is correct. 
2. Remove the State column

Reproduction steps:

1. Scan systems and use EDMC and "update" to force an update on EDDN 
2. Wait a few moments
3. Check the state of your faction in that system and compare to eddb.io and galmap

thoughts?

**Comment by SayakMukhopadhyay** [comment]
The thing is that Elite still provides the `state` field in the journal. I have asked about it and FDev said that they still use that value internally for some stuff, they wouldn't say what. What's important is that value is correct as far as EDDN is concerned. This is the relevant log from EDDN https://ross.eddb.io/eddn/log/670884334
```
{
    "$schemaRef": "https://eddn.edcd.io/schemas/journal/1",
     "header": {
        "gatewayTimestamp": "2021-02-27T17:51:54.078535Z",
         "softwareName": "E:D Market Connector [Windows]",
         "softwareVersion": "4.1.6",
         "uploaderID": "32eca846d9e14c3760fc8087dbb5719855675507"
    },
     "message": {
        "Body": "Pleiades Sector GW-W c1-13 A",
         "BodyID": 1,
         "BodyType": "Star",
         "Factions": [
            {
                "ActiveStates": [
                    {
                        "State": "Boom"
                    }
                ],
                 "Allegiance": "Independent",
                 "FactionState": "Boom",
                 "Government": "Cooperative",
                 "Happiness": "$Faction_HappinessBand2;",
                 "Influence": 0.480402,
                 "Name": "The Hive"
            },
             {
                "Allegiance": "Alliance",
                 "FactionState": "None",
                 "Government": "Democracy",
                 "Happiness": "$Faction_HappinessBand2;",
                 "Influence": 0.147739,
                 "Name": "Cooper Research Associates",
                 "RecoveringStates": [
                    {
                        "State": "Terrorism",
                         "Trend": 0
                    }
                ]
            },
             {
                "Allegiance": "Independent",
                 "FactionState": "Outbreak",
                 "Government": "Cooperative",
                 "Happiness": "$Faction_HappinessBand2;",
                 "Influence": 0.105528,
                 "Name": "Operation Ida"
            },
             {
                "Allegiance": "Independent",
                 "FactionState": "None",
                 "Government": "Corporate",
                 "Happiness": "$Faction_HappinessBand2;",
                 "Influence": 0.105528,
                 "Name": "Rational Logistics"
            },
             {
                "Allegiance": "Independent",
                 "FactionState": "None",
                 "Government": "Corporate",
                 "Happiness": "$Faction_HappinessBand2;",
                 "Influence": 0.160804,
                 "Name": "Janus Incorporated",
                 "RecoveringStates": [
                    {
                        "State": "PublicHoliday",
                         "Trend": 0
                    }
                ]
            }
        ],
         "Population": 1200000,
         "StarPos": [
            -77.375,
             -156.3125,
             -352.03125
        ],
         "StarSystem": "Pleiades Sector GW-W c1-13",
         "SystemAddress": 3657130971786,
         "SystemAllegiance": "Independent",
         "SystemEconomy": "$economy_Military;",
         "SystemFaction": {
            "FactionState": "Boom",
             "Name": "The Hive"
        },
         "SystemGovernment": "$government_Cooperative;",
         "SystemSecondEconomy": "$economy_None;",
         "SystemSecurity": "$SYSTEM_SECURITY_medium;",
         "event": "FSDJump",
         "timestamp": "2021-02-27T17:51:53Z"
    }
}
```
As for removing it from the UI, I don't know. I think providing as much info as possible is the way to go. Since I provide the active states along side the state, it shouldn't cause too much confusion.

What I can do is add a tooltip or something to inform users about this info.

**Comment by vanderaj** [comment]
I am more than satisfied with the color for active states drawing attention away from the broken state column.
