### ISSUE TITLE
API Faction endpoint produces incomplete list of systems compared to the Systems endpoint

### ISSUE THREAD

**Issue by cluster-fox** [Elite-Kode/elitebgs#271]
Behaviour was noted Using API v5:

Making an API call to the **?faction** endpoint with argument **name=** produces a list of 11 systems.
Making an API call to the **?systems** endpoint with argument **faction=** produces a list of 12 systems (over 2 pages).

Expected result is a list of 12 systems as per the **?systems** endpoint.

The faction in this particular case is _Cameron's Combat Services_
The missing system in this particular case is _Wirang_, EliteBGS-ID: _5a0611bed22c775be069e579_

Discrepancy was first observed on 14 Nov 2021.
Both lists were producing expected output on 13 Nov 2021. 

JSON output enclosed:
[json-files.zip](https://github.com/Elite-Kode/elitebgs/files/7537153/json-files.zip)

**Comment by SayakMukhopadhyay** [comment]
Thanks for the report, this has been manually fixed.
