### ISSUE TITLE
Endpoint /ticks does not return historical data

### ISSUE THREAD

**Issue by gmdvieira** [Elite-Kode/elitebgs#272]
When querying /ticks, even if I include timeMin, timeMax, only the last tick in the provided interval is returned.There is no 'history' field.

A quick check at the code appears to show that the definition of TickTimesV5 does not include history. Also, I could not find the definition of TickTimesHistoryV5.

**Comment by SayakMukhopadhyay** [comment]
A sample query which does return data https://elitebgs.app/api/ebgs/v5/ticks?timeMin=1639353600000&timeMax=1640276393012

Double check if the date format is correct.

**Comment by gmdvieira** [comment]
First, thanks mate, you are awesome.

I was following the documentation here: https://elitebgs.app/ebgs/docs/V5/definitions/TickTimesV5
and got sidetracked looking for the 'history' field. Never occurred to me to check the *other* entries in the array, because I assumed it would be a single one.

So, not a bug. A little adjustment to the docs would be great. If you point me to the source docs I can make a patch.

**Comment by SayakMukhopadhyay** [comment]
The docs in fact do state that the API responds with historical data. Check https://elitebgs.app/ebgs/docs/V5/paths/ticks/get
