### ISSUE TITLE
States displayed on Systems page should show system-specific states

### ISSUE THREAD

**Issue by 00Chaotic** [Elite-Kode/elitebgs#371]
The [Systems](https://elitebgs.app/systems) page seems to show the faction-wide state rather than the state of a faction within a specific system. It may be better for the information on the Systems page to remain specific to that system, and the faction-wide information can remain on the [Factions](https://elitebgs.app/factions) page.

I'll use my faction as an example.

One of our members was looking at the [Kuwema](https://elitebgs.app/systems/59e88513d22c775be001c20a) system when they noticed that the page said our faction was at war. However, this is because we're at war in a _different_ system. The below chart for Kuwema shows that our faction has been at war since 10 March, which is correct, but it's a war in a _different system_.

![image](https://user-images.githubusercontent.com/44113229/224456605-058c3d6f-0bf4-4871-9a63-940a6f58850a.png)

I'm willing to take a look into this, but wanted to raise an issue here first to get others' thoughts.

Is there a reason for that design decision? Are there reasons not to make this change?

**Comment by SayakMukhopadhyay** [comment]
What you are looking for is the Active State that is also listed.

**Comment by 00Chaotic** [comment]
Is there a reason for the other State to be present on the Systems page? Perhaps it would be better placed in the Factions page and/or re-naming the charts would help clarify which ones show general faction states and which are specific to the system in question.

**Comment by SayakMukhopadhyay** [comment]
Its there for legacy reasons. Also, frontier still provides the information for some reason and hence I continue to show it, Anyway, what you see is intended.

**Comment by 00Chaotic** [comment]
Alright, feel free to close this ticket if no changes are intended to be made.
